version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend-container
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: backend-container
    ports:
      - "8080:8080"