services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8080
    command: bash -c "npm install && npx nodemon"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "8080:8080"
    volumes:
      # Mount the source code for hot reloading
      - ./backend/src:/app/src
      # Mount the Maven cache directory
      - ~/.m2:/root/.m2
      - ./backend/target:/app/target
    command: ["mvn", "spring-boot:run"]